spring:
  datasource:
    url: jdbc:mariadb://localhost:7779/challympic?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: DB게정정보
    password: DB비밀번호
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      #test

server:
  port: 7777
  servlet:
    context-path: /challympic
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 키스토어비밀번호

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace